services:
  - mongodb
  - redis

language: node_js

node_js:
  - stable

branches:
  only:
    - master
    - develop

install:
  - yarn install
  - yarn global add codecov

script:
  - yarn coverage

after_success:
  - yarn codecov