services:
  - mongodb
  - redis
  - docker

language: node_js

node_js:
  - stable

branches:
  only:
    - master
    - develop

install:
  - yarn install
  - yarn global add codecov

script:
  - yarn coverage

after_success:
  - yarn codecov

after_deploy:
  - env > ./.env
  - yarn build
  - echo ${DOCKER_PW} > ./pw.txt
  - docker build -t ${DOCKER_ID}/${DOCKER_REPO}:latest .
  - cat ./pw.txt | docker login --username ${DOCKER_ID} --password-stdin
  - docker push ${DOCKER_ID}/${DOCKER_REPO}:latest