version: "3.7"

services:
    proxy:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy/proxy.conf:/etc/nginx/proxy.conf
            - ./proxy/cf.conf:/etc/nginx/cf.conf
            - ./proxy/allow-cloudflare-only.conf:/etc/nginx/allow-cloudflare-only.conf
        deploy:
            placement:
                constraints: [node.role == manager]
            resources:
                reservations:
                    cpus: "0.8"
                    memory: "800m"

            mode: replicated
            replicas: 1
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/nginx-health"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 10s

    express:
        image: pukuba/sunrin_api:latest
        deploy:
            placement:
                constraints: [node.role == worker]
            resources:
                reservations:
                    cpus: "0.8"
                    memory: "800m"
            mode: replicated
            replicas: 8

    redis:
        image: redis:latest
        deploy:
            placement:
                constraints: [node.role == manager]
            mode: replicated    
            resources:
                reservations:
                    cpus: "0.8"
                    memory: "800m"
            replicas: 1
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3